import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  Lightbulb, Loader2, Sparkles, TrendingUp, ArrowRight,
  Clock, Database, BarChart3
} from 'lucide-react';
import toast from 'react-hot-toast';
import { getInsights, listAnalyses } from '../utils/api';
import Sidebar from '../components/Sidebar';
import '../styles/settings.css';

const InsightsPage = () => {
  const navigate = useNavigate();
  const [insights, setInsights] = useState([]);
  const [analyses, setAnalyses] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      try {
        const [insRes, anRes] = await Promise.all([getInsights(), listAnalyses()]);
        setInsights(insRes.data);
        setAnalyses(anRes.data);
      } catch (err) {
        toast.error('Failed to load insights');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  const handleInsightClick = (analysisId) => {
    if (!analysisId) return;
    navigate(`/analysis/${analysisId}`);
    window.location.reload();
  };

  const formatDate = (dateStr) => {
    if (!dateStr) return '';
    const date = new Date(dateStr);
    const now = new Date();
    const diffMs = now - date;
    const diffMins = Math.floor(diffMs / 60000);
    const diffHrs = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 1) return 'Just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHrs < 24) return `${diffHrs}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  };

  const getAnalysisTitle = (analysisId) => {
    const a = analyses.find((x) => x.id === analysisId);
    return a?.title || 'Untitled Analysis';
  };

  if (loading) {
    return (
      <div className="chat-page">
        <Sidebar />
        <main className="settings-main">
          <div className="chat-loading">
            <Loader2 size={32} className="spin" />
            <p>Loading insights...</p>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="chat-page">
      <Sidebar />

      <main className="settings-main">
        <div className="settings-container">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="settings-header"
          >
            <h1>
              Insights <Lightbulb size={28} style={{ display: 'inline', verticalAlign: 'middle', color: '#f59e0b', marginLeft: 6 }} />
            </h1>
            <p>AI-generated business insights from all your analyses</p>
          </motion.div>

          {/* Stats Bar */}
          <motion.div
            className="stats-grid"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            style={{ marginBottom: 32 }}
          >
            <motion.div className="usage-card" whileHover={{ y: -3 }}>
              <div className="usage-icon"><Lightbulb size={18} /></div>
              <div className="usage-label">Total Insights</div>
              <div className="usage-value">{insights.length}</div>
              <div className="usage-limit">Generated by AI</div>
            </motion.div>

            <motion.div className="usage-card" whileHover={{ y: -3 }}>
              <div className="usage-icon"><BarChart3 size={18} /></div>
              <div className="usage-label">From Analyses</div>
              <div className="usage-value">{analyses.length}</div>
              <div className="usage-limit">Total chats</div>
            </motion.div>

            <motion.div className="usage-card" whileHover={{ y: -3 }}>
              <div className="usage-icon"><Sparkles size={18} /></div>
              <div className="usage-label">AI Model</div>
              <div className="usage-value" style={{ fontSize: 18 }}>Llama 3.3</div>
              <div className="usage-limit">70B params · Groq</div>
            </motion.div>
          </motion.div>

          {/* Insights Section */}
          <motion.div
            className="settings-section"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
          >
            <div className="section-head">
              <TrendingUp size={18} />
              <h2>All Insights</h2>
            </div>

            {insights.length === 0 ? (
              <div className="insight-page-empty">
                <Lightbulb size={48} />
                <h3>No insights yet</h3>
                <p>Ask questions about your data to generate AI-powered insights</p>
                <button
                  className="upgrade-btn"
                  onClick={() => navigate('/dashboard')}
                >
                  <Database size={16} /> Go to Dashboard
                </button>
              </div>
            ) : (
              <div className="insights-page-grid">
                {insights.map((ins, i) => (
                  <motion.div
                    key={ins.id}
                    className="insight-page-card"
                    onClick={() => handleInsightClick(ins.analysis_id)}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.05 * i, duration: 0.3 }}
                    whileHover={{ y: -2 }}
                  >
                    <div className="insight-page-icon">
                      <Lightbulb size={18} />
                    </div>

                    <p className="insight-page-text">{ins.description}</p>

                    <div className="insight-page-meta">
                      <Clock size={12} />
                      <span>{formatDate(ins.created_at)}</span>
                      <span style={{ color: 'var(--text-muted)' }}>·</span>
                      <span style={{
                        flex: 1,
                        whiteSpace: 'nowrap',
                        overflow: 'hidden',
                        textOverflow: 'ellipsis'
                      }}>
                        {getAnalysisTitle(ins.analysis_id)}
                      </span>
                      <ArrowRight size={12} style={{ flexShrink: 0 }} />
                    </div>
                  </motion.div>
                ))}
              </div>
            )}
          </motion.div>
        </div>
      </main>
    </div>
  );
};

export default InsightsPage;